### ISSUE TITLE
Clarify which versions of Anki are supported

### ISSUE THREAD

**Issue by houshuang** [gmcmanus/anki-roam-import#1]
I get this error, seems like it's trying to run it using Python 2? Not sure how to configure. I have Python 3 installed on my system. 

![image](https://user-images.githubusercontent.com/61575/75449975-465d0f80-596e-11ea-9a64-7a5fc43e38fc.png)

**Comment by gmcmanus** [comment]
What version of Anki are you using? Try using the latest version, 2.1.20.

Anki add-ons rely on the Python version and modules that are bundled with Anki, not on your system Python. It seems the typing module was added to Anki's bundled Python 6 months ago.
