### ISSUE TITLE
Choose import deck

### ISSUE THREAD

**Issue by MartinBernstorff** [gmcmanus/anki-roam-import#3]
Thank you so much for this add-on! It's _tremendously_ useful to me!

I'd love to import all the notes into an "inbox" deck for further sorting, but right now it just adds to my top-level deck. Could this be added to the config?

Thanks again.
Martin

**Comment by gmcmanus** [comment]
A new config item `deck_name` has been added which should solve your problem. See the documentation [here](https://github.com/gmcmanus/anki-roam-import#configuration). Update the addon (if you installed according to [the instructions here](https://github.com/gmcmanus/anki-roam-import#installation) then you can just use Tools -> Add-ons -> Check for Updates) and give it a try! Let me know if there are any issues with this.

**Comment by MartinBernstorff** [comment]
Incredible response time, thank you! :-)
